### ISSUE TITLE
__init__.py missing from beta2

### ISSUE THREAD

**Issue by pfig** [pinard/Pymacs#23]
Hi,

When I tried to install from beta2, pip gave the following error:

```
package init file 'Pymacs/__init__.py' not found (or not a regular file)
```

and (Aqua|E)macs would complain:

```
error: Pymacs helper did not start within 30 seconds
```

I then installed successfully from beta1.

Cheers,

Pedro

**Comment by leoliu** [comment]
Make sure every package relying on pymacs is up-to-date.

**Comment by pinard** [comment]
Pedro Figueiredo
reply@reply.github.com
writes:

> When I tried to install from beta2, pip gave the following error:
> package init file 'Pymacs/**init**.py' not found (or not a regular
> file)

Hello, Pedro.

Well, Pymacs/**init**.py has been deleted recently, so I presume pip has
to be adjusted somehow, by whoever linked pip and Pymacs.

François

P.S. Getting Pymacs into automatic installers is going to be part of my
next effort, I guess.  The Python installers do not install the Emacs
Lisp parts, and the Emacs installers do not really pay attention to
Python.  Installers also have their idiosyncrasies and requirements
about formatting, version nomenclature, and others things, each its own
of course.  Some people expect packages to fit and serve installers,
rather than installers adapting to packages.  Moreover, some installers
are competing, each claiming to be better than the others.  Maintainers
like me are lobbied for adopting one or another, which is a kind of
giving my vote.  To vote intelligently in that jungle requires study,
and burden.  But I might not escape it anymore :-).

**Comment by pfig** [comment]
Hi,

thanks for the reply, I hadn't realised it wasn't an accident :> I'm fairly new to Python, so I thought the installers used some language-wide mechanism, as opposed to each doing their own (tbh, I only know of easy_install and pip :) I fully agree that picking sides is complicated.

Thank you for the quick reply, and for Pymacs!
